### ISSUE TITLE
Alpha Channel Support

### ISSUE THREAD

**Issue by ZenithVal** [georgekhananaev/py-image-compressor#2]
I swapped RGB for RGBA in imageCompressor.py~ worked like a charm.

Would be nice to check the original image for alpha, and if so use RGBA instead of RGB. 
Could add a -t (transprency) or -a (alpha) command for this.

**Comment by georgekhananaev** [comment]
Hi, I made a little tweak in the imageCompressor. Now, instead of manually setting the mode with im = im.convert("RGB"), it cleverly figures it out on its own based on the image type as you suggested.

`if im.mode in ("RGBA", "LA") or (im.mode == "P" and "transparency" in im.info):
                im = im.convert("RGBA")
            else:
                im = im.convert("RGB")`

For the second part, which includes the options '-t' (for transparency) and '-a' (for alpha), I can add these later if you need. Right now, I am working on a substantial project and have limited availability. Feel free to open a new issue for these features. However, as it stands currently, I have thoroughly tested it, and it works well.
